In [2]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [5]:
df = pd.read_csv(r'D:\Scaledge_office_work\homeprices.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [7]:
df.bedrooms.median()

4.0

In [8]:
df.bedrooms = df.bedrooms.fillna(df.bedrooms.median())
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [9]:
reg = linear_model.LinearRegression()
reg.fit(df.drop('price', axis = 1), df.price)

LinearRegression()

In [10]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [11]:
reg.intercept_

221323.00186540408

In [12]:
reg.predict([[3000, 3,40]])

array([498408.25158031])

In [13]:
reg.predict([[2500, 4, 5]])

array([578876.03748933])

In [14]:

df = pd.read_csv(r'D:\Scaledge_office_work\hiring.csv')
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [19]:
m = df['test_score(out of 10)'].mean()

In [20]:
import math 
m = math.floor(m)
m

7

In [21]:
df['test_score(out of 10)'] = df['test_score(out of 10)'].fillna(m)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    7.0                           7      72000
7     eleven                    7.0                           8      80000

In [22]:
df.fillna('zero', inplace = True)

In [27]:
pip install word2number
from word2number import w2n

In [33]:
df['experience'] = df['experience'].apply(w2n.word_to_num)

In [34]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    7.0                           7      72000
7          11                    7.0                           8      80000

In [35]:
reg = linear_model.LinearRegression()
reg.fit(df[['experience','test_score(out of 10)','interview_score(out of 10)']], df['salary($)'])

LinearRegression()

In [36]:
reg.predict([[2,9,6]])

array([53713.86677124])

In [37]:
reg.predict([[12,10,10]])

array([93747.79628651])